# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the files
COPY . .

# Build the TypeScript project
RUN npm run build

# Expose port if necessary (optional, MCP communicates over stdio)

# Start the MCP server
CMD ["node", "build/index.js"]
